name: Testim E2E
on: [push]

jobs:
    run-testimio-cli:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                node-version: '16'
                # You can also change 'lts' to any supported LTS Node.js version.
            - run: npm install -g @testim/testim-cli
            - run: testim --token "PWUGAyHlh9Am5FQttFSIPQTMwC1uyikS6IHmWR6IBN2UKln8SZ" --project "hZG4nxbuXbnfOd9WYggx" --grid "Testim-Grid" --mode "extension" --branch "main"
